### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by DKotsyuba** [dalinaum/atom-android#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.1
**System**: Ubuntu 15.10
**Thrown From**: [android](https://github.com/dalinaum/atom-android) package, v0.1.0
### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /home/pluto/.atom/packages/android/lib/android.coffee:30

TypeError: Cannot read property 'getPath' of undefined
    at Object.module.exports.Android.buildGradle (/home/pluto/.atom/packages/android/lib/android.coffee:30:37)
    at atom-workspace.subscriptions.add.atom.commands.add.android:build-gradle (/home/pluto/.atom/packages/android/lib/android.coffee:17:88)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -6:28.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -4:58.2.0 core:save (atom-text-editor.editor.is-focused)
     -4:57 core:save-as (atom-text-editor.editor.is-focused)
     -4:33.7.0 settings-view:open (atom-text-editor.editor.is-focused)
     -3:58.1.0 core:confirm (atom-text-editor#autoclose-html.forceInline.editor.mini.is-focused)
     -3:48.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -3:44.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:41.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -3:40.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -3:04.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:36.4.0 find-and-replace:show (div.panels-item)
     -2:33.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:33.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  3x -1:53.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  8x -0:23.4.0 core:backspace (div.panels)
     -0:01.1.0 android:build-gradle (div.package-detail.panels-item)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
android, v0.1.0
autoclose-html, v0.19.0
language-groovy-cloned-from-java, v0.3.0

# Dev
No dev packages
```

**Comment by championswimmer** [comment]
bump

**Comment by ghost** [comment]
Why not use android studio or AIDE

**Comment by st-f** [comment]
Buuump

**Comment by dalinaum** [comment]
Sorry, I don't have enough time to develop this package.
